# Copyright © 2020 Advanced Micro Devices, Inc. All rights reserved

set(CPACK_GENERATOR "DEB;RPM" CACHE STRING "Package types to build")
# set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE 1)
set(CPACK_COMPONENTS_ALL dev tests)
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_RPM_COMPONENT_INSTALL ON)

set(CPACK_COMPONENT_TESTS_DESCRIPTION
  "Embers unit tests")

set(CPACK_PACKAGE_NAME "embers")
set(CPACK_DEBIAN_DEV_PACKAGE_NAME "embers")
set(CPACK_RPM_DEV_PACKAGE_NAME "embers")
set(CPACK_DEBIAN_TESTS_PACKAGE_NAME ${EMBERS_TEST_PKG_NAME})
set(CPACK_RPM_TESTS_PACKAGE_NAME ${EMBERS_TEST_PKG_NAME})

set(CPACK_PACKAGE_VENDOR "Advanced Micro Devices, Inc.")
set(CPACK_PACKAGE_VERSION ${PACKAGE_VERSION_STRING})
set(CPACK_PACKAGE_CONTACT "Advanced Micro Devices, Inc.")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A header-only HIP library with a slew of user-focused features for GPU test development")

# Debian package specific variables
if(DEFINED ENV{CPACK_DEBIAN_PACKAGE_RELEASE})
  set(CPACK_DEBIAN_PACKAGE_RELEASE $ENV{CPACK_DEBIAN_PACKAGE_RELEASE})
else()
  set(CPACK_DEBIAN_PACKAGE_RELEASE "local")
endif()
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE
  "https://github.com/ROCm/embers")

set(CPACK_DEBIAN_TESTS_PACKAGE_DEPENDS "embers")
set(CPACK_DEBIAN_TESTS_PACKAGE_PROVIDES ${EMBERS_TEST_PKG_NAME})

# RPM specific variables
set(CPACK_RPM_TESTS_PACKAGE_REQUIRES "embers")
set(CPACK_RPM_TESTS_PACKAGE_PROVIDES ${EMBERS_TEST_PKG_NAME})

if(DEFINED ENV{CPACK_RPM_PACKAGE_RELEASE})
  set(CPACK_RPM_PACKAGE_RELEASE $ENV{CPACK_RPM_PACKAGE_RELEASE})
else()
  set(CPACK_RPM_PACKAGE_RELEASE "local")
endif()

# 'dist' breaks manual builds on debian systems due to empty Provides
execute_process(COMMAND rpm --eval %{?dist}
  RESULT_VARIABLE PROC_RESULT
  OUTPUT_VARIABLE EVAL_RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(PROC_RESULT EQUAL "0" AND NOT EVAL_RESULT STREQUAL "")
  string(APPEND CPACK_RPM_PACKAGE_RELEASE "%{?dist}")
endif()

set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")

include(CPack)
